### ISSUE TITLE
Retrieve the AccountTable

### ISSUE THREAD

**Issue by Baltox** [fxcm/fxcmrest-php#1]
@fxcm-pguz Hi, i want to execute a simple GET request to retrieve the AccountTable.

Can you show me a example ?

This is my code (doesn't work) :
```
$rest->request('GET', '/trading/get_model?model=Account', [], function($code, $data) {
                var_dump($data);
            });
```
Thank you.

API Doc : https://fxcm.github.io/rest-api-docs/#operation/tradingTable%2FAccountTable

**Comment by FXCMAPI** [comment]
issue been resolved, closing it.
