### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by Troodi** [fxcm/fxcmrest-php#3]
PHP 7.3
Sample code not work on dev-master
socket error: Unable to read from stream: stream_get_contents(): SSL:

With real API 
```
$config = new \FxcmRest\Config([
  'host' => 'api.fxcm.com',
  'token' => '***',
]);
```

With demo API
`Uncaught Error: Class 'FxcmRest\Exception' not found in E:\OSpanel\domains\TradingView\vendor\fxcm\fxcmrest\src\SocketIO.php:169`

```
$config = new \FxcmRest\Config([
  'host' => 'api-demo.fxcm.com',
  'token' => '***',
]);
```

In SocketIO class in wsdata method i get $packet:
```
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

**Comment by fxcm-dhalpert** [comment]
please replace line 84 in Socketio.php file with this line:

$request = "GET /socket.io/?EIO=3&transport=websocket&sid={$this->options->sid}&access_token={$this->config->token()} HTTP/1.1\r\n"

**Comment by Troodi** [comment]
> please replace line 84 in Socketio.php file with this line:
> 
> $request = "GET /socket.io/?EIO=3&transport=websocket&sid={$this->options->sid}&access_token={$this->config->token()} HTTP/1.1\r\n"

Thank you!

**Comment by johndkn** [comment]
Hello, 
Would it be possible to update the repository with this change?
Thanks in advance

**Comment by PlanetTheCloud** [comment]
This issue has delayed our projects by a few days as we thought it was our server that was rejected by Cloudflare (as it was working a few hours prior).
